/* genatlas — build-time tool: rasterize a TrueType font into an anti-aliased
 * glyph atlas C source (kernel/src/font_atlas.c). Runs on the HOST (full libc +
 * float), so the kernel never needs stb_truetype or floating point.
 *
 *   cc tools/genatlas.c -o genatlas -Ithird_party/stb
 *   ./genatlas third_party/stb/font.ttf kernel/src/font_atlas.c
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#define STB_TRUETYPE_IMPLEMENTATION
#include "stb_truetype.h"

/* Pixel sizes for text scales 1,2,3. Tuned for the window-manager chrome. */
static const int PX[3] = {15, 27, 38};
#define FIRST 32
#define COUNT 95

int main(int argc, char **argv) {
    if (argc != 3) { fprintf(stderr, "usage: genatlas <font.ttf> <out.c>\n"); return 1; }

    FILE *f = fopen(argv[1], "rb");
    if (!f) { perror("font"); return 1; }
    fseek(f, 0, SEEK_END); long n = ftell(f); fseek(f, 0, SEEK_SET);
    unsigned char *ttf = malloc(n);
    if (fread(ttf, 1, n, f) != (size_t)n) { fprintf(stderr, "read\n"); return 1; }
    fclose(f);

    stbtt_fontinfo font;
    if (!stbtt_InitFont(&font, ttf, stbtt_GetFontOffsetForIndex(ttf, 0))) {
        fprintf(stderr, "bad font\n"); return 1;
    }

    FILE *o = fopen(argv[2], "w");
    if (!o) { perror("out"); return 1; }
    fprintf(o, "/* Generated by tools/genatlas.c from a TrueType font. Do not edit. */\n");
    fprintf(o, "#include \"font_atlas.h\"\n\n");

    short px_arr[3], asc_arr[3], lh_arr[3], sp_arr[3], cell_arr[3];

    /* coverage byte arrays */
    for (int s = 0; s < 3; ++s) {
        float scale = stbtt_ScaleForPixelHeight(&font, (float)PX[s]);
        int asc, desc, gap;
        stbtt_GetFontVMetrics(&font, &asc, &desc, &gap);
        px_arr[s]  = (short)PX[s];
        asc_arr[s] = (short)(asc * scale + 0.5f);
        lh_arr[s]  = (short)((asc - desc + gap) * scale + 0.5f);
        { int aw, lsb; stbtt_GetCodepointHMetrics(&font, ' ', &aw, &lsb); sp_arr[s] = (short)(aw * scale + 0.5f); }
        { int cw = 0; for (int c = '0'; c <= '9'; ++c) { int aw, lsb; stbtt_GetCodepointHMetrics(&font, c, &aw, &lsb);
              int a = (int)(aw * scale + 0.5f); if (a > cw) cw = a; } cell_arr[s] = (short)cw; }

        for (int i = 0; i < COUNT; ++i) {
            int cp = FIRST + i, w = 0, h = 0, xo = 0, yo = 0;
            unsigned char *bmp = stbtt_GetCodepointBitmap(&font, scale, scale, cp, &w, &h, &xo, &yo);
            if (bmp && w > 0 && h > 0) {
                fprintf(o, "static const unsigned char g%d_%d[%d]={", s, cp, w * h);
                for (int k = 0; k < w * h; ++k) fprintf(o, "%d,", bmp[k]);
                fprintf(o, "};\n");
            }
            if (bmp) stbtt_FreeBitmap(bmp, 0);
        }
    }

    /* atlas table */
    fprintf(o, "\nconst struct atlas_glyph FONT_ATLAS[ATLAS_SIZES][ATLAS_COUNT]={\n");
    for (int s = 0; s < 3; ++s) {
        float scale = stbtt_ScaleForPixelHeight(&font, (float)PX[s]);
        fprintf(o, "  {\n");
        for (int i = 0; i < COUNT; ++i) {
            int cp = FIRST + i, w = 0, h = 0, xo = 0, yo = 0, aw = 0, lsb = 0;
            unsigned char *bmp = stbtt_GetCodepointBitmap(&font, scale, scale, cp, &w, &h, &xo, &yo);
            stbtt_GetCodepointHMetrics(&font, cp, &aw, &lsb);
            int adv = (int)(aw * scale + 0.5f);
            int has = (bmp && w > 0 && h > 0);
            if (has)
                fprintf(o, "    {%d,%d,%d,%d,%d,g%d_%d},\n", w, h, xo, yo, adv, s, cp);
            else
                fprintf(o, "    {0,0,0,0,%d,0},\n", adv);
            if (bmp) stbtt_FreeBitmap(bmp, 0);
        }
        fprintf(o, "  },\n");
    }
    fprintf(o, "};\n\n");

    fprintf(o, "const short FONT_ATLAS_PX[ATLAS_SIZES]={%d,%d,%d};\n", px_arr[0], px_arr[1], px_arr[2]);
    fprintf(o, "const short FONT_ATLAS_ASCENT[ATLAS_SIZES]={%d,%d,%d};\n", asc_arr[0], asc_arr[1], asc_arr[2]);
    fprintf(o, "const short FONT_ATLAS_LINEH[ATLAS_SIZES]={%d,%d,%d};\n", lh_arr[0], lh_arr[1], lh_arr[2]);
    fprintf(o, "const short FONT_ATLAS_SPACE[ATLAS_SIZES]={%d,%d,%d};\n", sp_arr[0], sp_arr[1], sp_arr[2]);
    fprintf(o, "const short FONT_ATLAS_CELLW[ATLAS_SIZES]={%d,%d,%d};\n", cell_arr[0], cell_arr[1], cell_arr[2]);

    fclose(o);
    fprintf(stderr, "genatlas: wrote %s (sizes %d/%d/%d px)\n", argv[2], PX[0], PX[1], PX[2]);
    return 0;
}
